plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - bin/*
    - log/*
    - tmp/*
    - vendor/bundle/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/ClassLength:
  Max: 135

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
